### ISSUE TITLE
Why is the future information removed in every layer?

### ISSUE THREAD

**Issue by eduOS** [tobyyouup/conv_seq2seq#16]
The future information should only be avoided in the first stage as articulated in [this post](https://mchromiak.github.io/articles/2017/Sep/12/Transformer-Attention-is-all-you-need/#decoder), but in this repository it is removed in [each layer of the three layers](https://github.com/tobyyouup/conv_seq2seq/blob/master/seq2seq/encoders/conv_encoder_utils.py#L173). 

Am I wrong somewhere?

Please help and point me in the right direction. Thanks very much.

**Comment by tobyyouup** [comment]
@eduOS  The future information should be avoided in every layers of the decoder.

**Comment by eduOS** [comment]
@tobyyouup Thanks very much for your reply, :) but I still have a quick question as bellow. Hoping that you could spare a little time to answer. 

1. In the paper it is said that the k elements should removed to avoid future information:

> Specifically, we pad the input by k − 1 elements on both the left and right side by zero vectors, and then remove k elements from the end of the convolution output.

2. but in [your implementation](https://github.com/tobyyouup/conv_seq2seq/blob/master/seq2seq/encoders/conv_encoder_utils.py#L173) only k-1 elements are removed(and thus the length remains). 

`    next_layer = next_layer[:,0:-kwidths_list[layer_idx]+1,:]`

3. plus, in the [original lua code](https://github.com/facebookresearch/fairseq/blob/master/fairseq/models/fconv_model.lua#L305), it is the first and the last k-1 tokens that are removed: 

`        block:add(nn.Narrow(2, 1, -kwidth))`

What has been confusing me is that, according to the paper, the output of each layer will decrease by 1 token, thus "to avoid future information" seems a bit self-explaining; however in your code, the length keeps the same, which is beautifully implemented, but I don't get the point of "avoid future information".. What do you mean by "avoid the future information"?

It seems that the three versions: the paper, your code and the original code may to some extent conflict to each other. 

Best regards, 
Lerner

**Comment by tobyyouup** [comment]
@eduOS  I think removing k tokens in the paper is wrong.  It should be k-1, otherwise the length will mismatch.

**Comment by eduOS** [comment]
@tobyyouup OK. I got it. 

It makes the ith output relates only to the first i tokens by slipping the next sequence of the next layer to the left by k % 2 units(to counteract the convolution on the right side).
