### ISSUE TITLE
Where to initialize hash tables in a new model?

### ISSUE THREAD

**Issue by anglil** [tobyyouup/conv_seq2seq#3]
Hi, I created a new model that is similar to your conv_seq2seq model but contains some hashtables. I'm wondering where to initialize those hashtables using tf.tables_initializer? I couldn't find where a session is started in the codebase in which one can do table and variable initialization. Thanks!

**Comment by tobyyouup** [comment]
Hi anglil, the code is based on tensorflow's contrib API, where the estimator and experiment is defined. The session is started in contrib API, So the you may add tf.tables_initializer near that codes.

**Comment by anglil** [comment]
Thanks.
